<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXm3In1R\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXm3In1R/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXm3In1R.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXm3In1R\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXm3In1R\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Xm3In1R',
    'container.build_id' => '79f60f39',
    'container.build_time' => 1556471442,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXm3In1R');
