<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFTxMJjv\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFTxMJjv/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFTxMJjv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFTxMJjv\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerFTxMJjv\srcApp_KernelProdContainer([
    'container.build_hash' => 'FTxMJjv',
    'container.build_id' => 'e47f74d1',
    'container.build_time' => 1555879278,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFTxMJjv');
