<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQh98ily\srcApp_Kernel.envDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQh98ily/srcApp_Kernel.envDebugContainer.php') {
    touch(__DIR__.'/ContainerQh98ily.legacy');

    return;
}

if (!\class_exists(srcApp_Kernel.envDebugContainer::class, false)) {
    \class_alias(\ContainerQh98ily\srcApp_Kernel.envDebugContainer::class, srcApp_Kernel.envDebugContainer::class, false);
}

return new \ContainerQh98ily\srcApp_Kernel.envDebugContainer([
    'container.build_hash' => 'Qh98ily',
    'container.build_id' => '353b5b27',
    'container.build_time' => 1555879244,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQh98ily');
