<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUCvlLCC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUCvlLCC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUCvlLCC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUCvlLCC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUCvlLCC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UCvlLCC',
    'container.build_id' => 'abf149e7',
    'container.build_time' => 1557050342,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUCvlLCC');
