<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWSrANYs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWSrANYs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWSrANYs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWSrANYs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWSrANYs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WSrANYs',
    'container.build_id' => '88d04b90',
    'container.build_time' => 1556839439,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWSrANYs');
