<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxcb5hF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxcb5hF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGxcb5hF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGxcb5hF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGxcb5hF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Gxcb5hF',
    'container.build_id' => 'fac7d8ee',
    'container.build_time' => 1556111175,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxcb5hF');
