<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIoSFxNV\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIoSFxNV/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIoSFxNV.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIoSFxNV\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIoSFxNV\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IoSFxNV',
    'container.build_id' => 'e7894fb3',
    'container.build_time' => 1556442387,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIoSFxNV');
