<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBQN5DG7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBQN5DG7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBQN5DG7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBQN5DG7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBQN5DG7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BQN5DG7',
    'container.build_id' => 'f766564a',
    'container.build_time' => 1556066259,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBQN5DG7');
